### ISSUE TITLE
What is the fastest way to append items to an existing vector?

### ISSUE THREAD

**Issue by drkameleon** [faragon/libsrt#26]
This is what I'm currently trying:

```c
    srt_vector* vec = sv_alloc_t(SV_U8,100000000);

    double start = getCurrentTime();
    Byte* inner_buff = sv_get_buffer(vec);
    for (int i=0; i<100000000; i++) {
        sv_push_u(&vec,(Byte)i);
    }
    
    printf("total time (srt): %g\n",getCurrentTime()-start);

    sv_free(&vec);
```

I've also tried `sv_get_buffer` after allocating enough memory and setting the elements like `vec[x]=i` but it doesn't seem to be working.

Any suggestions?

**Comment by faragon** [comment]
@drkameleon hi, the fastest way is to do a sv_resize(), and then with a sv_get buffer have direct access to the _uint8_t *_ elements (you would do a similar thing when using C++).

BTW, on branch issue#21 I'm doing a rewrite for faster safe-access (2 to 3x faster), and also adding floating-point support for vector and map/hash-map.
