### ISSUE TITLE
"All rights reserved." in license

### ISSUE THREAD

**Issue by qlcom** [faragon/libsrt#31]
do you really want that?
will you consider removing it?

**Comment by faragon** [comment]
I keep all rights, but I allow a Open Source license (BSD 3-Clause), please check the LICENSE file.

The BSD 3-Clause is quite permissive, so it allows commercial usage and it is not "viral" (in the sense of e.g. GPL-v3).

If that license is not enough for you, tell me which is your need, and I will consider it.

**Comment by qlcom** [comment]
I mean that sentence doesn't sounds good.

**Comment by qlcom** [comment]
there is projects that use bsd style license but don't contain that sentence.

**Comment by faragon** [comment]
I followed the BSD template for the 3-clause license:

https://en.wikipedia.org/wiki/BSD_licenses

In the future I may consider switching to the "0-clause" BSD or other "public domain"-like formulas, if that was your concern.

**Comment by qlcom** [comment]
> In the future I may consider switching to the "0-clause" BSD or other "public domain"-like formulas, if that was your concern.

That will be nice to have.

you can use a 3-clause bsd style license without that sentence. like being used in https://git.sr.ht/~sircmpwn/core.sr.ht/tree/master/LICENSE

**Comment by faragon** [comment]
May be. But I'm not a lawyer, so I stick to the default template.

**Comment by qlcom** [comment]
i am not a lawyer also.
but i think not having that sentence (like in the template for the 2-clause license on wikipedia) makes the license better.
