### ISSUE TITLE
Is libsrt thread-safe?

### ISSUE THREAD

**Issue by seirios** [faragon/libsrt#34]
Hello! I'm thinking of adopting this library for my projects, but I'm worried about thread safety. According to Paul Hsieh's [String Library Comparisons](https://bstring.sourceforge.net/features.html) table, `libsrt` has `Thread Safety: No`. Could you please explain what parts of the library are not thread-safe? Thanks!

**Comment by niuggg** [comment]
good

**Comment by faragon** [comment]
@seirios Hi, Paul is right, libsrt is intentionally not thread safe: It is "thread safe" for concurrent read-only operations, e.g. initialization, fill the data, and use the data from N threads, but not for write or read+write concurrent operation. E.g. it is as "thread safe" as the equivalent C++ STL containers, which are also not thread safe for concurrent read+write or write+write.
